### PR TITLE
Add _named methods for serializing structs as maps

### PR DESCRIPTION
**Pull request by semtexzv**
Hello, first PR :).
I had a problem with rmp-serde serializing structs as arrays so I added methods with _named suffix that would fix this. I also removed utlity methods from lib.rs and added reexports from encode.rs and decode.rs, since those methods were exactly same

Sorry for all the formatting spam.

### CODE REVIEW

**Comment by 3Hren** [comment]
Hi! Thanks for the contribution.

Could you please exclude all style-changing stuff from the PR? It's hard to figure out what was changed.

**Comment by termoshtt** [comment]
Good work. I need this PR.
I've remove formatting part at https://github.com/termoshtt/msgpack-rust/pull/1
@semtexzv Could you check my branch and rebase to there?
Or, should I open another PR?

**Comment by hjiayz** [comment]
good job

**Comment by 3Hren** [comment]
Merged in #140.

**Pull request closed without merging**
