### PR TITLE
Replace Serializer wrappers with equivalent Config wrappers

### LINKED ISSUE #205: Structs in lists ignore ext handler settings
When using `with_struct_map`, I generally expected structs being encoded as maps to be applied recursively, to all structs serialized. This is sometimes the case, but if any structs are nested within options or arrays, then the behavior is no longer applied. Structures within arrays or options are serialized as arrays.

For instance, this version of the `round_struct_as_map` test fails:

```rust
#[test]
fn round_struct_as_vec_map() {
    use rmps::decode::from_slice;
    use rmps::to_vec_named;

    #[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
    struct Dog1 {
        name: String,
        age: u16,
    }
    #[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
    struct Dog2 {
        age: u16,
        name: String,
    }

    let dog1 = Dog1 {
        name: "Frankie".into(),
        age: 42,
    };

    let data = vec![dog1];

    let serialized: Vec<u8> = to_vec_named(&data).unwrap();
    let deserialized: Vec<Dog2> = from_slice(&serialized).unwrap();

    let dog2 = &deserialized[0];

    assert_eq!(dog2.name, "Frankie");
    assert_eq!(dog2.age, 42);
}
```

With the error message: `Syntax("invalid type: string \"Frankie\", expected u16")`.

### PR DESCRIPTION
**Pull request by daboross**
Fixes #205.

This replaces the Serializer wrapper system introduced in #146 with an equivalent system of having the serializer store a "config" structure, and wrapping that config.

This is a breaking change:
- it removes the `Ext` trait, replacing its functionality with methods on `Serializer`
- it makes `Serializer` generic over `C`, a config
- it replaces `StructMapSerializer<Serializer<W>>` with `Serializer<W, StructMapConfig<DefaultConfig>>` and `StructTupleSerializer<Serializer<W>>` with `Serializer<W, StructTupleConfig<DefaultConfig>>`

However, this strategy should allow for easily adding new configuration options without breaking things in the future. We can simply add a new method to the hidden `SerializerConfig` trait, create a new wrapper config, and add a new method on `Serializer` to enable using it.

---

I hope I'm not intruding by trying to do a big change like this. I just need the fix for my own usage of the crate, and I'd rather PR to the official repository than maintain my own fork of it.

### CODE REVIEW

**Comment by daboross** [comment]
@kornelski Since we're now both contributors with access to this project: if you have time, what do you think of the changes here?

There are ways we could fix #205 without a complete overhaul, but when I looked into the code, it seemed hard to make things foolproof while keeping the "entire decoder is wrapped" pattern.

---

Just to note, I did implement an option for encoding enum variant names as strings on top of this, it's just not part of this PR. Didn't want to stop fixing the existing problems (#205) just to get in extra features. That code is at https://github.com/daboross/msgpack-rust/commits/v2-variant-string-fix, with the main commit being https://github.com/daboross/msgpack-rust/commit/d91315779f4b3542650a2d088504ba7c2a5efea7.

**Comment by kornelski** [comment]
That looks good to me. 

I'd like to release the current stable master first before making breaking changes.

**Comment by daboross** [comment]
Sounds good!

I was thinking that it might be alright since https://github.com/3Hren/msgpack-rust/pull/146 was already a breaking change for `rmp-serde`, but I realize that was a while ago and it's been marked as `0.14.0` forever, even if that hasn't been released to crates.io. It would be the first release with #205, but I guess that's OK as long as we're releasing a fix for it in `0.15.0`?

**Comment by kornelski** [comment]
I've been using 0.14 via git URL for a while.

**Comment by daboross** [comment]
Ah, reasonable. 0.14.0 and 0.15.0 it is then!

If we're releasing new versions, I can work on updating all the changelogs?

**Comment by kornelski** [comment]
Sure

**Pull request merged**
