### PR TITLE
rmp-serde: Switch from separate structures to config type parameters

### LINKED ISSUE #172: rmp_serde: Open to optionally tagging enums with names?
Right now enums seem to be represented as a discriminant, even in the "named" variation.

See this example

```rust
extern crate rmp_serde;
extern crate serde;
#[macro_use]
extern crate serde_derive;

#[derive(Debug, Serialize, Deserialize)]
enum SomeEnum {
    FieldA(String),
    FieldB(String),
}

#[derive(Debug, Serialize, Deserialize)]
enum FutureVersionOfThatEnum {
    FieldB(String),
    FieldA(String),
}

fn main() {
    let input = SomeEnum::FieldA("Hello, world!".to_owned());
    let bytes = rmp_serde::to_vec_named(&input).unwrap();
    let output: FutureVersionOfThatEnum = rmp_serde::from_slice(&bytes).unwrap();
    println!("Output: {:?}", output);
}
```

I expect this to output "FieldA", but it outputs "FieldB". This is the one thing stopping me from switching from json to messagepack right now where my use case otherwise completely fits it.

Are there any future plans for adding a configuration option to tag enums by name rather than by integer discriminant?

If you'd be open to this, but there aren't currently future plans, I could definitely put together a pull request.

### PR DESCRIPTION
**Pull request by daboross**
This is an alternative to #179. I prefer this PR, but it's a breaking change.

This switches from using wrapper structs to encoding different configurations to using type parameters. Specifically, `Serializer` is now generic over `StructFieldEncoding` and `EnumVariantEncoding`. The parameters control how struct fields are encoded and how enum variants are encoded respectively.

This allows the same zero-cost configuration, with a few advantages:

- This configuration pattern requires less boilerplate of serde methods when introducing new configuration
-  This pattern can represent both enum variant configuration and struct field configuration without any conflicts. The one alternative I found, written in #179, had semi-incorrect output if `with_struct_map_encoding` was used after `with_variant_integer_encoding` because of the way serde methods work and the fact that all configurations were implemented as wrapper structs.
- This allows adding a runtime-decided configuration option with very little added code. Someone can now have the same serializer type serializing with a different configuration depending on what enum value it's fed on creation (see `Serializer::with_field_encoding` and `Serializer::with_variant_encoding`).
  - In the old method, the serializer type for serializing structs as maps was always different than the serializer for structs as tuples. The former was `StructMapSerializer<Serializer>` and the latter `Serializer`.
  - In this generics-based method, we can do the same thing as before with `Serializer<StructMapEncoding>` vs `Serializer<StructTupleEncoding>`, but we can also have `Serializer<RuntimeDecidedEncoding>` with a runtime switch.

My main motivation for doing this is correctly implementing string-enum-variants, but the other side-effects are nice.

Now for the disadvantages:
- This is a breaking change.
  - I found it very hard to find a way to implement these changes while keeping backwards compatibility.
  - This _might_ not be a bad thing depending on whether we also want to merge #176, another breaking change with great benefits, at the same time.
  - There are two ways in which this is breaking:
    - All type signatures which mention `StructMapSerializer` and `StructTupleSerializer` are now broken, as these types no longer exist.
    - `Ext` is removed in favor of regular methods on `Serializer`
    - The encoding of a struct-like enum was different in `StructMapSerializer` and `StructTupleSerializer` than it is in `Serializer`. The ext serializers encoded variant/enum as `[variant_index, data]` while the main serializer encoded `{variant_index => data}`. Now all encoders implement `{variant_index/name => data}`.
- This makes the rust code technically more complicated. It's a cleaner and smaller design, but it uses more complicated trait-based stuff and this isn't really friendly to people newer to rust.
  - I find serde implementations in general to be pretty complicated, so I don't see this as too much of a downside, but it's good to note.

The version implemented in #179 is not as nice, but it's backwards compatible.

---

With that said, I'm extremely open to feedback. I don't have much experience with this codebase and I've exclusively worked with the `rmp-serde` crate implementing this.

I'd be happy with this being merged today, but as mentioned I'm only experienced in rust and rust idioms, not in this codebase or style. If there's anything you feel could be done better, please mention it, and I'll try to fix the PR up.

Fixes #172, supersedes and closes #179, supersedes and closes #154.

### CODE REVIEW

**Comment by daboross** [comment]
I've forced pushed a few times trying to get travis to work. The bug that was breaking things seems to be fixed with serde version 1.0.81 though, so this should be all good!

I also added a test copied from #179, and a few convenience functions for manually specifying both configuration options without having to create a whole `Serializer`. Should be pretty straightforward? I've added examples to the documentation of most if not all not-completely-obvious functions.

**Comment by 3Hren** [comment]
Hi!
The diff is so huge, I need time to understand things :)

**Comment by daboross** [comment]
Alright - thanks!

I did change quite a bit, feel free to ask any questions. Hope I'm not intruding too much by changing the whole configuration system to be generic zero-length types with static methods rather than wrapper types.

**Comment by daboross** [comment]
I was just looking at some of the history of this crate, and I hadn't before. I didn't realize this essentially undoes https://github.com/3Hren/msgpack-rust/pull/146.

Because of your reasons for switching to separate structures in the first place, I'm closing this. Going to try to get #179 to work well instead.

**Pull request closed without merging**
