### PR TITLE
Initial support for serde

### PR DESCRIPTION
**Pull request by erickt**
This PR adds support for a serde serializer. Be aware that this can't quite land yet as it depends on https://github.com/serde-rs/serde/pull/134. It currently passes all the tests, but since I don't really know msgpack, it's possible I may have implemented something incorrectly.

I tried to match your style, but please feel free to hack it up any way you choose.

### CODE REVIEW

**Comment by 3Hren** [comment]
Wow, this is great!

So much code! It definitely takes amount of time to check this, but I accept it anyway after all CI checks pass.

Special thanks for the tests, there aren't much people who writes them.

Currently I see that Travis reports build errors, can you take a look please?

**Comment by 3Hren** [comment]
:+1: 
Waiting for https://github.com/serde-rs/serde/pull/134

**Comment by erickt** [comment]
@3Hren: I've pushed up serde 0.5.1 which has the backend changes. Can you re-run the travis builds and see if it works?

**Comment by 3Hren** [comment]
Done.

**Comment by 3Hren** [comment]
Thanks!

**Pull request merged**
