### PR TITLE
Add zero-copy strings and bytes deserializing in rmp-serde

### LINKED ISSUE #75: Deserialize strings and bytes without intermediate buffer with serde deserializer
There is [buf](https://github.com/3Hren/msgpack-rust/blob/b0132f75882cc57c17f1e319ef07b99b0c94b8bc/rmp-serde/src/decode.rs#L203) field in `Deseralizer` which is used for strings and bytes deseralization: functions [read_str_data](https://github.com/3Hren/msgpack-rust/blob/b0132f75882cc57c17f1e319ef07b99b0c94b8bc/rmp/src/decode.rs#L1083) and [read_full](https://github.com/3Hren/msgpack-rust/blob/b0132f75882cc57c17f1e319ef07b99b0c94b8bc/rmp/src/decode.rs#L1359) takes a references to this buffer and `Deserializer`'s `R: Read`, read some bytes from `R: Read` and writes it to the buffer.

Looks like it's unnecessary overhead if `R` is `&[u8]` because it's possible to use this bytes directly from `&[u8]`.

I think it would be nice to have two different options:
1. deserialize from any generic `R: Read`, so we need in intermediate buffer,
2. deserialize from slice, without intermediate buffer.

### PR DESCRIPTION
**Pull request by knsd**
Implement special Read trait with two readers: SliceReader & ReadReader. SliceReader can be slightly faster for strings and bytes deserializing.

Fixes #75.

### CODE REVIEW

**Comment by arthurprs** [comment]
Do you have any numbers for the speed improvement here?

**Comment by hhatto** [comment]
FYI

in case of my environment. MacOSX 10.11.6 MacBook Pro (Retina, 13-inch, Early 2015)

`3Hren.bench` is dacd2aed2201a48dc27375435a038d8ae3976b38

```
$ cargo benchcmp 3Hren.bench knsd.bench
 name                 3Hren.bench ns/iter  knsd.bench ns/iter  diff ns/iter  diff %
 bench_strings_1000   93,831               104,822                   10,991  11.71%
 bench_strings_10000  994,918              1,088,413                 93,495   9.40%
 bench_strings_5000   491,697              549,947                   58,250  11.85%
```

**Comment by arthurprs** [comment]
Am I reading that right, the zero-copy branch is slower?

**Comment by hhatto** [comment]
> Am I reading that right, the zero-copy branch is slower?

Yes

**Comment by knsd** [comment]
This pr introduces new `Deserializer::from_slice` constructor and there was a bug with old `Deserializer::new` (renamed to `Deserializer::from_read`) constructor, it was a little slower. Guess it fixed now:

```
 name                 master ns/iter  zerocopy ns/iter  diff ns/iter  diff %
 bench_strings_1000   69,756          65,303                  -4,453  -6.38%
 bench_strings_10000  691,042         672,020                -19,022  -2.75%
 bench_strings_5000   350,014         334,441                -15,573  -4.45%
```

Anyway it's a bad benchmark for this case because of needless allocations and utf-8 check, this pr affects bytes deserializing mostly, for example we can use [this synthetic benchmark](https://gist.github.com/knsd/dd0263749f20f88d9a466495c6fc507f).

```
 name                 master_bytes ns/iter  zero_copy_from_slice_bytes ns/iter  diff ns/iter   diff %
 bench_strings_1000   14,129                6,333                                     -7,796  -55.18%
 bench_strings_10000  141,937               67,005                                   -74,932  -52.79%
 bench_strings_5000   74,119                33,059                                   -41,060  -55.40%
```

**Pull request merged**
