### PR TITLE
ci: resurrect code coverage

### PR DESCRIPTION
**Pull request by euclio**
Trying to see if this passes.

### CODE REVIEW

**Comment by euclio** [comment]
So, it didn't work. It seems to me like the easiest fix would be to just use cargo workspaces, but Rust 1.13 doesn't have workspace support :(

**Comment by 3Hren** [comment]
We can upload coverage from nightly only.

**Comment by 3Hren** [comment]
Great job! Is there anything left to do or I can merge?

**Comment by euclio** [comment]
There's still an issue where coverage is recorded multiple times. Trying to fix that, but I'm wrestling with some bash syntax on travis :P

**Comment by euclio** [comment]
@3Hren Ok! Should be good to merge!

**Comment by 3Hren** [comment]
Thanks!

**Pull request merged**
