### PR TITLE
Deserializer & Serializer for Value

### LINKED ISSUE #101: Implement `serde::Serializer` and `serde::Deserializer` for `rmpv::Value`
`serde_json` contains structs that implement these traits, which provides efficient ways to convert between serializable values and `Value`s. It's a huge ergonomics win, and the library can also provide `to_value` and `to_msgpack` methods for convenience.

It also would prevent the need for a `From` impl for all but the simplest types.

### PR DESCRIPTION
**Pull request by 3Hren**
- [x] Value.
- [x] ValueRef.
- [x] Update changelog.

Closes #101.

### CODE REVIEW

**Comment by 3Hren** [comment]
Unfortunately the issue discovered (asymmetry of encoding/decoding `Value`) requires to break `Value::U64` and `Value::I64` and to replace them with `Value::PosInt` (with 0 included) and `Value::NegInt`.

@euclio thoughts?

**Comment by euclio** [comment]
Hm, I'm not sure I understand the issue fully.

**Comment by 3Hren** [comment]
`to_value(from_value(Value::I64(128))) == Value::U64(128)`, because we always chose the most compact integer representation.

**Comment by euclio** [comment]
Why not just encode the types directly? `i8` -> `int8`, `u64` -> `uint64` etc.?

**Comment by 3Hren** [comment]
From [here](https://github.com/msgpack/msgpack/blob/master/spec.md#serialization-type-to-format-conversion):
> If an object can be represented in multiple possible output formats, serializers SHOULD use the format which represents the data in the smallest number of bytes.

**Comment by euclio** [comment]
Ah, I see. Why not replace it with `Value::Integer` to mirror the source types in the spec?

**Comment by 3Hren** [comment]
I think so too. Thanks :)

**Comment by 3Hren** [comment]
Finally done.

Closes https://github.com/3Hren/msgpack-rust/issues/60, https://github.com/3Hren/msgpack-rust/issues/101, https://github.com/3Hren/msgpack-rust/issues/102 and https://github.com/3Hren/msgpack-rust/issues/105.

**Pull request merged**
