### PR TITLE
Fix rmp-serde name in crates.io table

### PR DESCRIPTION
**Pull request by dbrgn**

### CODE REVIEW

**Comment by 3Hren** [comment]
This was intentional.

**Comment by dbrgn** [comment]
Sorry, I meant to ask in the PR description whether it's intentional or not :)

So why is it called `rmps` there if the crate is called `rmp-serde`?

**Comment by 3Hren** [comment]
Mostly for historical reasons, and because crates.io doesn't allow aliases. When `rustc-serialize` was not dead while `serde` was born it was really inconsistent to name a crate just `rmps`, because of ambiguity.

Now when `rustc-serialize` is deprecated `rmps` is fully belongs to `serde` binding, but `crates.io` forces me to support the old name.

Also I like short names :)

**Comment by dbrgn** [comment]
You could deprecate the old crate and publish a new one :) I'd also prefer `rmps`.

But the current approach works fine as well.

**Comment by 3Hren** [comment]
I though about this. But likely this will lead to even more confusing and backward-compatibility issues. I personally just `extern crate rmp_serde as rmps` to be happy :)

**Pull request closed without merging**
